/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
  ],
  safelist: [
    'bg-gradient-to-r',
    'from-primary-500',
    'to-secondary-500',
    'from-primary-600',
    'to-secondary-600',
    'from-primary-900',
    'to-secondary-900',
    'text-primary-600',
    'dark:text-primary-400',
    'text-gray-500',
    'animate-fade-in',
    'animate-slide-in-right',
    'animate-spin'
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'var(--primary-50)',
          100: 'var(--primary-100)',
          200: 'var(--primary-200)',
          300: 'var(--primary-300)',
          400: 'var(--primary-400)',
          500: 'var(--primary-500)',
          600: 'var(--primary-600)',
          700: 'var(--primary-700)',
          800: 'var(--primary-800)',
          900: 'var(--primary-900)',
          950: 'var(--primary-950)',
        },
        secondary: {
          50: 'var(--secondary-50)',
          100: 'var(--secondary-100)',
          200: 'var(--secondary-200)',
          300: 'var(--secondary-300)',
          400: 'var(--secondary-400)',
          500: 'var(--secondary-500)',
          600: 'var(--secondary-600)',
          700: 'var(--secondary-700)',
          800: 'var(--secondary-800)',
          900: 'var(--secondary-900)',
          950: 'var(--secondary-950)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
      },
      boxShadow: {
        'xl': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        'inner-lg': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
        'primary-sm': '0 2px 4px 0 var(--primary-500)',
        'primary-md': '0 4px 8px 0 var(--primary-500)',
        'primary-lg': '0 10px 15px -3px var(--primary-500)',
        'primary-xl': '0 20px 25px -5px var(--primary-500)',
        'primary-2xl': '0 25px 50px -12px var(--primary-500)',
        'secondary-sm': '0 2px 4px 0 var(--secondary-500)',
        'secondary-md': '0 4px 8px 0 var(--secondary-500)',
        'secondary-lg': '0 10px 15px -3px var(--secondary-500)',
        'secondary-xl': '0 20px 25px -5px var(--secondary-500)',
        'secondary-2xl': '0 25px 50px -12px var(--secondary-500)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-in-out',
        'slide-down': 'slideDown 0.5s ease-in-out',
        'slide-in-right': 'slideInRight 0.5s ease-in-out',
        'slide-in-left': 'slideInLeft 0.5s ease-in-out',
        'float-slow': 'float 8s ease-in-out infinite',
        'float-medium': 'float 6s ease-in-out infinite alternate',
        'float-fast': 'float 4s ease-in-out infinite alternate',
        'float-reverse': 'floatReverse 7s ease-in-out infinite alternate',
        'spin-slow': 'spin 15s linear infinite',
        'neural-pulse': 'neuralPulse 3s ease-in-out infinite',
        'neural-glow': 'neuralGlow 4s ease-in-out infinite alternate',
        'neural-path': 'neuralPath 10s linear infinite',
        'neural-spark': 'neuralSpark 2s ease-out infinite',
        'neural-wave': 'neuralWave 8s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideInLeft: {
          '0%': { transform: 'translateX(-20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        float: {
          '0%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
          '100%': { transform: 'translateY(0)' },
        },
        floatReverse: {
          '0%': { transform: 'translateY(0) rotate(45deg)' },
          '50%': { transform: 'translateY(10px) rotate(45deg)' },
          '100%': { transform: 'translateY(0) rotate(45deg)' },
        },
        neuralPulse: {
          '0%': { transform: 'scale(0.95)', opacity: '0.7' },
          '50%': { transform: 'scale(1.05)', opacity: '1' },
          '100%': { transform: 'scale(0.95)', opacity: '0.7' },
        },
        neuralGlow: {
          '0%': { boxShadow: '0 0 5px 0 rgba(14, 165, 233, 0.3)' },
          '50%': { boxShadow: '0 0 20px 5px rgba(14, 165, 233, 0.6)' },
          '100%': { boxShadow: '0 0 5px 0 rgba(14, 165, 233, 0.3)' },
        },
        neuralPath: {
          '0%': { strokeDashoffset: '1000' },
          '100%': { strokeDashoffset: '0' },
        },
        neuralSpark: {
          '0%': { transform: 'scale(0)', opacity: '1' },
          '50%': { transform: 'scale(1)', opacity: '0.8' },
          '100%': { transform: 'scale(1.5)', opacity: '0' },
        },
        neuralWave: {
          '0%': { transform: 'translateX(-100%) scaleY(0.5)', opacity: '0.2' },
          '50%': { transform: 'translateX(0%) scaleY(1)', opacity: '0.5' },
          '100%': { transform: 'translateX(100%) scaleY(0.5)', opacity: '0.2' },
        },
      },
    },
  },
  plugins: [],
} 